version: '3.3'
services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: portfolio-react_node
    tty: true
    working_dir: /usr/src/app/
    volumes:
      - type: bind
        source: ${PWD}
        target: /usr/src/app
    environment:
      REACT_APP_API_ENDPOINT: ${REACT_APP_API_ENDPOINT}
      REACT_APP_LOGIN_SHORTCUT: ${REACT_APP_LOGIN_SHORTCUT}
    ports:
      - 8080:8080
      - 8001:8001
      - 8000:8000
      - 3001:3001

  web:
    image: nginx
    container_name: portfolio-react_web
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ${PWD}/docker/web/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ${PWD}/build
        target: /usr/share/nginx/html